# Generated by Django 2.2.2 on 2019-06-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeardLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_user', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=255)),
                ('event_points', models.IntegerField()),
                ('event_team', models.CharField(max_length=10)),
                ('event_message', models.TextField()),
            ],
        ),
    ]
