# Generated by Django 2.2.2 on 2019-06-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bearddb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beardlog',
            name='event_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beardlog',
            name='event_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beardlog',
            name='event_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beardlog',
            name='event_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
