# Generated by Django 2.2.2 on 2019-06-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bearddb', '0002_auto_20190612_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beardlog',
            name='event_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='beardlog',
            name='event_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='beardlog',
            name='event_team',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='beardlog',
            name='event_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
