# Generated by Django 2.2.2 on 2019-06-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bearddb', '0003_auto_20190612_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='beardlog',
            name='event_test',
            field=models.BooleanField(default=True),
        ),
    ]
